import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {serve} from '../../scripts/serve-browser-tools.mjs';
const {server, url} = await serve();
let browser;
try {
  browser = await chromium.launch({headless: true, ...(process.env.KURO_CHROMIUM_PATH ? {executablePath: process.env.KURO_CHROMIUM_PATH} : {})});
  const page = await browser.newPage();
  const external = [];
  page.on('request', request => {if (!request.url().startsWith(url)) external.push(request.url());});
  await page.goto(url);
  await page.waitForFunction(() => window.browserTools);
  const results = await page.evaluate(async () => {
    const {createToolHost, toToolMessage} = await import('./client.js');
    const grants = ['tool/js', 'tool/python', 'tool/python-js-bridge', 'fs/read', 'fs/write'];
    const host = createToolHost({capabilities: grants, timeoutMs: 30000});
    const call = (name, args, h = host, options = {}) => h.call({id: 'test-' + name, type: 'function', function: {name, arguments: JSON.stringify(args)}}, options);
    const results = {};
    results.js = await call('js', {code: "globalThis.priorCall = 42; console.log('日本語'); console.error('err'); fs.writeFile('out.txt', fs.readFile('in.txt') + inputs.suffix); ({answer: 42, network: typeof fetch, dom: typeof document})", inputs: {suffix: '✓'}, files: {'in.txt': 'あ'}, exportFiles: ['out.txt']});
    results.python = await call('python', {code: "import json, math\nprint('日本語')\nwith open('in.txt') as f: text = f.read()\nwith open('out.txt', 'w') as f: f.write(text + inputs['suffix'])\n{'answer': math.factorial(5), 'text': text}", inputs: {suffix: '✓'}, files: {'in.txt': 'あ'}, exportFiles: ['out.txt']});
    results.jsError = await call('js', {code: "throw new Error('bad JS')"});
    results.pyError = await call('python', {code: "raise ValueError('bad Python')"});
    results.async = await call('js', {code: '(async () => { const x = await Promise.resolve(40); return x + 2; })()'});
    results.asyncError = await call('js', {code: "Promise.reject(new Error('async error'))"});
    results.pendingError = await call('js', {code: 'new Promise(() => {})'});
    results.freshJs = await call('js', {code: 'typeof priorCall'});
    results.freshPy = await call('python', {code: "import os\nos.path.exists('out.txt')"});
    let created = 0;
    const denied = createToolHost({makeWorker: () => {created++; throw Error('must not execute');}});
    results.denied = await call('js', {code: '42'}, denied);
    results.pyBridgeDenied = await call('python', {code: '42'}, createToolHost({capabilities: ['tool/python'], makeWorker: () => {created++; throw Error('must not execute');}}));
    results.pathDenied = await call('js', {code: '42', files: {'../secret': 'x'}}, denied);
    results.fsDenied = await call('js', {code: '42', exportFiles: ['a']}, createToolHost({capabilities: ['tool/js'], makeWorker: () => {created++; throw Error('must not execute');}}));
    results.createdDenied = created;
    const timed = createToolHost({capabilities: grants, timeoutMs: 3000});
    results.timeout = await call('js', {code: 'while (true) {}'}, timed);
    results.pyTimeout = await call('python', {code: "print('loop-started', flush=True)\nwhile True: pass"}, createToolHost({capabilities: grants, timeoutMs: 8000}));
    const controller = new AbortController();
    setTimeout(() => controller.abort(), 200);
    results.cancelled = await call('js', {code: 'while (true) {}'}, host, {signal: controller.signal});
    results.outputLimit = await call('js', {code: "console.log('あ'.repeat(2000))"}, createToolHost({capabilities: grants, maxOutputBytes: 1024}));
    results.resultLimit = await call('python', {code: "'あ' * 2000"}, createToolHost({capabilities: grants, maxOutputBytes: 1024}));
    results.recovery = await call('js', {code: 'inputs.a + inputs.b', inputs: {a: 20, b: 22}});
    results.message = toToolMessage(results.recovery);
    return results;
  });
  console.log(JSON.stringify(results, null, 2));
  assert.equal(results.js.receipt['kuro/exit-code'], 0);
  assert.deepEqual(results.js.result, {answer: 42, network: 'undefined', dom: 'undefined'});
  assert.equal(results.js.receipt['kuro/stdout'], '日本語\n');
  assert.equal(results.js.receipt['kuro/stderr'], 'err\n');
  assert.equal(results.js.files['out.txt'], 'あ✓');
  assert.equal(results.python.receipt['kuro/exit-code'], 0);
  assert.deepEqual(results.python.result, {answer: 120, text: 'あ'});
  assert.equal(results.python.files['out.txt'], 'あ✓');
  assert.equal(results.python.receipt['kuro/stdout'], '日本語\n');
  assert.equal(results.async.result, 42);
  for (const name of ['jsError', 'pyError', 'asyncError', 'pendingError']) assert.equal(results[name].receipt['kuro/exit-code'], 1, name);
  assert.equal(results.freshJs.result, 'undefined');
  assert.equal(results.freshPy.result, false);
  for (const name of ['denied', 'pyBridgeDenied', 'pathDenied', 'fsDenied']) assert.equal(results[name].receipt['kuro/exit-code'], 126, name);
  assert.equal(results.createdDenied, 0);
  assert.equal(results.denied.receipt['kuro/isolation'], 'none');
  for (const name of ['timeout', 'pyTimeout']) {
    assert.equal(results[name].receipt['kuro/exit-code'], 124, name);
    assert.equal(results[name].receipt['kuro/timed-out?'], true, name);
  }
  assert.equal(results.cancelled.receipt['kuro/exit-code'], 130);
  assert.equal(results.outputLimit.receipt['kuro/exit-code'], 125);
  assert.equal(results.resultLimit.receipt['kuro/exit-code'], 125);
  assert.equal(results.pyTimeout.receipt['kuro/stdout'], 'loop-started\n');
  assert.equal(results.recovery.result, 42);
  assert.equal(results.message.role, 'tool');
  assert.equal(results.message.tool_call_id, 'test-js');
  assert.equal(JSON.parse(results.message.content).result, 42);
  assert.deepEqual(external, [], 'runtimes must load locally, no CDN');
  console.log('PASS: real Chromium JS/Python tool calls, files, denials, errors, deadlines, cancellation, limits, fresh state and recovery');
} finally {
  await browser?.close();
  await new Promise(resolve => server.close(resolve));
}
